#!/bin/bash -x

echo
echo

/usr/local/bin/wake_krokus.sh

/usr/bin/apt-get update
/usr/bin/apt-file update

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/etc/domeny:/etc/local/bin:.


#sleep 1
#/usr/local/bin/gen_priv_bind_zone.sh

sleep 1 
/usr/sbin/tmpreaper -m 72 /tmp
/usr/sbin/tmpreaper -v -m 2d /var/cache/apt/archives


sleep 1
/usr/local/bin/listallpkgs

sleep 1
/usr/sbin/ntpdate ntp.icm.edu.pl

sleep 1
/usr/sbin/ntpdate ntp.task.gda.pl

sleep 1
/usr/local/bin/bind_zone_sync.sh

sleep 1
/etc/init.d/bind9 restart

sleep 1
/usr/local/bin/bind_zone_sync.sh


sleep 1
du -x -S / | sort -rn | head -n 100 > /etc/local/du_root

/etc/init.d/fail2ban restart

history -c

/usr/local/bin/disable_ipv6_accept_ra.sh
/usr/local/bin/drop_ip6tables.sh
